import Link from "next/link";
import "./globals.css";
import { Inter } from "next/font/google";
import Image from "next/image";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "AVS_NEXT",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="flex gap-1 border border-gray-600  p-1">
          <Link href={"/"}>
            <Image
              className="relative dark:drop-shadow-[0_0_0.3rem_#ffffff70] dark:invert"
              src="/next.svg"
              alt="Next.js Logo"
              width={180}
              height={37}
              priority
            />
          </Link>
          <nav className="flex gap-2 uppercase">
            <Link href={"/"}>Home</Link>
            <Link href={"/blog"}>Blog</Link>
          </nav>
        </header>
        {children}
      </body>
    </html>
  );
}
